apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dont-want-to-be-here
  namespace: dev2
  labels:
    app.kubernetes.io/name: dont-want-to-be-here
    app.kubernetes.io/part-of: dont-want-to-be-here
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
spec:
  params:
    - name: image_scanner_template_name
      value: image-scanner-template
    - name: scanning_source_policy
      value: lax-scan-policy
    - name: scanning_image_policy
      value: lax-scan-policy
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: java
  source:
    git:
      url: ssh://git@github.com/Mpluya/greeter-source-canary-sample-package.git
      ref:
        branch: main
